# Generated by Django 2.2.6 on 2019-11-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoreArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_slug', models.SlugField(blank=True)),
                ('article_text', models.TextField(blank=True)),
                ('article_title', models.CharField(blank=True, max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='LoreKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('articles', models.ManyToManyField(to='lore.LoreArticle')),
            ],
        ),
    ]
