# Generated by Django 2.2.6 on 2019-11-04 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('skill', '0001_initial'),
        ('character', '0002_auto_20191103_2032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.SlugField(max_length=5)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.SlugField(max_length=5)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('production_cost', models.PositiveIntegerField(default=0)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item_Category')),
                ('skill_to_produce', models.ForeignKey(limit_choices_to={'is_production_skill': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='skill.Skill')),
                ('skill_to_use', models.ManyToManyField(related_name='can_use', to='skill.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.CharField(default=item.models.generate_timestamp, max_length=50)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('produced_by_pc', models.BooleanField(default=False)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('expires_date', models.DateField(default=item.models.get_default_expiration_date)),
                ('is_treasure', models.BooleanField(default=False)),
                ('school', models.CharField(choices=[('E', 'Elemental'), ('S', 'Spirit'), ('L', 'Light'), ('D', 'Darkness'), ('N', 'None'), ('O', 'Other')], default='O', max_length=1)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item_Type')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character')),
                ('skill_to_use', models.ManyToManyField(to='skill.Skill')),
            ],
        ),
    ]
