# Generated by Django 2.2.6 on 2019-11-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spells',
            field=models.ManyToManyField(to='spell.Spell'),
        ),
    ]
