# Generated by Django 2.2.6 on 2019-11-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('school', models.CharField(choices=[('E', 'Elemental'), ('S', 'Spirit'), ('L', 'Spirit - Light'), ('D', 'Spirit - Darkness'), ('N', 'None'), ('O', 'Other')], default='O', max_length=1)),
                ('duration', models.CharField(max_length=100)),
                ('radius', models.CharField(max_length=100)),
            ],
        ),
    ]
