# Generated by Django 2.2.6 on 2019-11-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='damage_or_healing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='incantation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_damage_spell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_healing_spell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='radius',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
