# Generated by Django 2.2.6 on 2019-11-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0002_auto_20191104_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='subschool',
            field=models.CharField(choices=[('L', 'Light'), ('D', 'Darkness'), ('U', 'Unspecified')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(choices=[('E', 'Elemental'), ('S', 'Spirit'), ('N', 'None'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
