# Generated by Django 2.2.6 on 2019-11-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='character_subrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character_Subrace'),
        ),
    ]
