# Generated by Django 2.2.6 on 2019-11-04 01:32

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0002_auto_20191103_2032'),
        ('address', '0002_auto_20160213_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player_limit', models.PositiveIntegerField(default=0)),
                ('treasure', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('public_notes', models.TextField(blank=True, max_length=500)),
                ('staff_notes', models.TextField(blank=True, max_length=500)),
                ('plot_notes', models.TextField(blank=True, max_length=500)),
                ('logistics_notes', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('P', 'PC'), ('N', 'NPC'), ('O', 'Other')], default='P', max_length=1)),
                ('character_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('treasure_taken', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('treasure_returned', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.SlugField(max_length=5)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('default_hours', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('pcs_and_npcs', models.BooleanField(default=True)),
                ('is_leo', models.BooleanField(default=True)),
                ('default_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Location')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event_Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Location'),
        ),
    ]
