# Generated by Django 2.2.6 on 2019-11-04 01:32

import address.models
import character.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('player_notes', models.TextField(blank=True, max_length=500)),
                ('plot_notes', models.TextField(blank=True, max_length=500)),
                ('logistics_notes', models.TextField(blank=True, max_length=500)),
                ('admin_notes', models.TextField(blank=True, max_length=500)),
                ('bank', models.DecimalField(decimal_places=1, default=22.0, max_digits=6)),
                ('xp', models.DecimalField(decimal_places=4, default=50.0, max_digits=8)),
                ('hp', models.PositiveIntegerField(default=25)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('character_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to=character.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Character_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.SlugField(max_length=5)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Character_Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('costuming_notes', models.TextField(blank=True, max_length=300)),
                ('is_pc_race', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_logistics', models.BooleanField(default=False)),
                ('is_plot', models.BooleanField(default=False)),
                ('is_in_leo', models.BooleanField(default=False)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('unspent_hours', models.PositiveIntegerField(default=0)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character_Subrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('character_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character_Race')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
            ],
        ),
    ]
