# Generated by Django 2.2.6 on 2019-11-04 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
        ('character', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character_skill',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill.Skill_Option'),
        ),
        migrations.AddField(
            model_name='character_skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character_Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_race',
            field=models.ForeignKey(limit_choices_to={'is_pc_race': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character_Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_subrace',
            field=models.ForeignKey(limit_choices_to={'character_race': models.ForeignKey(limit_choices_to={'is_pc_race': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character_Race')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character_Subrace'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
