# Generated by Django 2.2.6 on 2019-11-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20191103_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_subrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character_Subrace'),
        ),
    ]
