# Generated by Django 2.2.6 on 2019-11-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20191104_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_skill',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill.Skill_Option'),
        ),
    ]
