# Generated by Django 2.2.6 on 2019-11-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20191104_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='admin_notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='logistics_notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='plot_notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='character_race',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='character_subrace',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
