# Generated by Django 2.2.6 on 2019-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20191107_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_race',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
