# Generated by Django 2.2.6 on 2019-11-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20191107_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rewrites_available',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
