# Generated by Django 2.2.6 on 2019-11-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_option',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('AW', 'At-Will'), ('Pa', 'Passive'), ('Pr', 'Production'), ('PD', 'Per-Day')], default='Pa', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill_option',
            name='bonus_skill',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_bonus_skill': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_for_prof', to='skill.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='skill_option',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill.Skill_Option_Category'),
        ),
        migrations.AlterField(
            model_name='skill_option_category',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='skill.Skill'),
        ),
    ]
