# Generated by Django 2.2.6 on 2019-11-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20191104_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='prereq',
            field=models.ManyToManyField(blank=True, null=True, related_name='prereq_of', to='skill.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='replaces_skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='replaced_by', to='skill.Skill'),
        ),
    ]
