# Generated by Django 2.2.6 on 2019-11-08 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20191104_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill.Skill_Category'),
        ),
    ]
