# Generated by Django 2.2.6 on 2019-11-10 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20191107_1626'),
        ('skill', '0004_auto_20191108_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racial_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=999)),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Character_Class')),
                ('character_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Character_Race')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.Skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Racial_Skill_Cost',
        ),
    ]
