# Generated by Django 2.2.6 on 2019-11-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_auto_20191109_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='has_bonus_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='replacement_is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
