# Generated by Django 2.2.6 on 2019-11-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_auto_20191110_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_option_category',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill_option_category',
            name='skill',
            field=models.ManyToManyField(null=True, related_name='category', to='skill.Skill'),
        ),
    ]
