# Generated by Django 2.2.6 on 2019-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20191107_1626'),
        ('skill', '0008_auto_20191110_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='available_to_races',
            field=models.ManyToManyField(to='character.Character_Race'),
        ),
    ]
