# Generated by Django 2.2.6 on 2019-11-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_skill_option_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='available_to_races',
            field=models.ManyToManyField(blank=True, to='character.Character_Race'),
        ),
    ]
