# Generated by Django 2.2.6 on 2019-11-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_auto_20191110_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_option',
            name='bonus_skill',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_bonus_skill': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_for_prof', to='skill.Skill'),
        ),
    ]
