# Generated by Django 2.2.6 on 2019-11-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20191107_1626'),
        ('skill', '0012_auto_20191110_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=999)),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Character_Class')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.Skill')),
                ('skill_option', models.ManyToManyField(blank=True, to='skill.Skill_Option')),
            ],
        ),
    ]
